# Generated by Django 3.2.25 on 2025-09-02 12:05

from django.db import migrations, models
import django.db.models.deletion
import sortedm2m.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('abdellah_collections', '0001_initial'),
        ('products', '0002_sizeguide_product_size_guide'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(choices=[('orders_shipping', 'orders & shipping'), ('payment', 'payment'), ('returns', 'returns & exchanges'), ('size_fit', 'size & fit'), ('products', 'products & materials'), ('offers', 'offers & discounts'), ('account', 'my account'), ('care', 'care instructions'), ('store_policy', 'store policies')], max_length=100)),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField(default=0, help_text='Order for display')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['heading', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ImageBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('desktop_image', models.ImageField(upload_to='images/banners/desktop/')),
                ('mobile_image', models.ImageField(upload_to='images/banners/mobile/')),
                ('link', models.ForeignKey(blank=True, help_text='Leave Blank to All Products', null=True, on_delete=django.db.models.deletion.CASCADE, to='abdellah_collections.collection')),
            ],
        ),
        migrations.CreateModel(
            name='FeaturedCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('collection_order', models.PositiveIntegerField(default=0)),
                ('products', sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, related_name='featured_in', to='products.Product')),
                ('view_all_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_collections', to='abdellah_collections.collection')),
            ],
            options={
                'ordering': ['collection_order'],
            },
        ),
    ]
