# Generated by Django 4.1.13 on 2025-08-25 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('abdellah_collections', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('desktop_image', models.ImageField(upload_to='images/banners/desktop/')),
                ('mobile_image', models.ImageField(upload_to='images/banners/mobile/')),
                ('link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='abdellah_collections.collection')),
            ],
        ),
    ]
