# Generated by Django 4.1.13 on 2025-08-26 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abdellah_shoping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(choices=[('orders', 'orders'), ('shipping', 'shipping'), ('payment', 'payment'), ('returns', 'returns & refunds'), ('size_fit', 'size & fit'), ('products', 'products & materials'), ('offers', 'offers & discounts'), ('account', 'my account'), ('care', 'care instructions'), ('store_policy', 'store policies')], max_length=100)),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField(default=0, help_text='Order for display')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['heading', 'order'],
            },
        ),
    ]
