# Generated by Django 3.2.25 on 2025-08-26 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abdellah_shoping', '0002_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='faq',
            name='heading',
            field=models.CharField(choices=[('orders_shipping', 'orders & shipping'), ('payment', 'payment'), ('returns', 'returns & exchanges'), ('size_fit', 'size & fit'), ('products', 'products & materials'), ('offers', 'offers & discounts'), ('account', 'my account'), ('care', 'care instructions'), ('store_policy', 'store policies')], max_length=100),
        ),
    ]
