# Generated by Django 3.1.12 on 2025-08-23 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abdellah_collections', '0003_auto_20250822_2237'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'verbose_name': 'Collection', 'verbose_name_plural': 'Collections'},
        ),
    ]
