# Generated by Django 3.1.12 on 2025-08-22 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='last_joined',
            new_name='last_logined',
        ),
    ]
