# Generated by Django 4.2.24 on 2025-09-07 18:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='pincode',
            field=models.CharField(default='', help_text='Enter 6 digit PIN code', max_length=6, validators=[django.core.validators.RegexValidator('^\\d{6}$', message='Enter a valid 6-digit PIN code')]),
            preserve_default=False,
        ),
    ]
