# Generated by Django 3.1.12 on 2025-08-22 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='Category_image',
            new_name='category_image',
        ),
    ]
