# Generated by Django 4.2.24 on 2025-09-22 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Confirmed', 'Confirmed'), ('Fullfilled', 'Fullfilled'), ('Cancelled', 'Cancelled')], default='New', max_length=50),
        ),
    ]
