# Generated by Django 4.1.13 on 2025-08-25 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SizeGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/size_guides/')),
                ('table_data', models.JSONField(default=dict, help_text='Enter JSON in the format:<br>{<br>  "columns": ["XS", "S", "M", "L", "XL", "XXL"],<br>  "rows": [<br>    {"name": "Bust", "values": [34, 36, 38, 40, 42, 44]},<br>    {"name": "Waist", "values": [26, 28, 30, 32, 34, 36]},<br>    {"name": "Hips", "values": [36, 38, 40, 42, 44, 46]}<br>  ]<br>}')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='size_guide',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.sizeguide'),
        ),
    ]
