# Generated by Django 4.2.24 on 2025-09-04 11:55

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20250903_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='more_info',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
