# Generated by Django 4.2.24 on 2025-09-10 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_productgallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_image',
        ),
    ]
